[custom.all.gradekeeper]
type = "local"
path = "."
ipkg = "gradekeeper.ipkg"
test = "test/test.ipkg"

[custom.all.gradekeeper-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.Md]
type = "local"
path = "/home/george/Tools/Md"
ipkg = "Md.ipkg"

[custom.all.IdrisTime]
type = "local"
path = "/home/george/Tools/IdrisTime"
ipkg = "IdrisTime.ipkg"



