[custom.all.gradekeeper-idris]
type = "local"
path = "."
ipkg = "gradekeeper-idris.ipkg"
test = "test/test.ipkg"

[custom.all.gradekeeper-idris-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.Md]
type = "local"
path = "/home/george/Tools/Md"
ipkg = "Md.ipkg"

[custom.all.IdrisTime]
type = "local"
path = "/home/george/Tools/IdrisTime"
ipkg = "IdrisTime.ipkg"

[custom.all.csv-idris]
type = "local"
path = "/home/george/Tools/csv-idris"
ipkg = "csv-idris.ipkg"


